# Generated by Django 5.2.9 on 2025-12-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("director", models.CharField(max_length=32)),
                ("acotr", models.CharField(max_length=32)),
                ("release", models.PositiveIntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("default", "------"),
                            ("action", "액션"),
                            ("romance", "로맨스"),
                            ("SF", "SF"),
                            ("comedy", "코미디"),
                            ("documentary", "다큐멘터리\x1f"),
                        ],
                        default="------",
                        max_length=32,
                    ),
                ),
                ("star", models.DecimalField(decimal_places=1, max_digits=2)),
                ("runningtime", models.PositiveIntegerField()),
                ("review_content", models.TextField()),
            ],
        ),
    ]
