# Generated by Django 5.2.9 on 2025-12-30 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Review", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="acotr",
            new_name="actor",
        ),
    ]
