# Generated by Django 5.2.9 on 2025-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Review", "0002_rename_acotr_review_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("default", "------"),
                    ("action", "액션"),
                    ("romance", "로맨스"),
                    ("SF", "SF"),
                    ("comedy", "코미디"),
                    ("documentary", "다큐멘터리\x1f"),
                ],
                default="default",
                max_length=32,
            ),
        ),
    ]
